#ifndef _ALTERA_HPS_H_
#define _ALTERA_HPS_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc' in
 * file '/cygdrive/c/Users/gutha.3/Desktop/FPGA_Projects/qkd_reciever/soc.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'mem1', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'MEM1_'.
 * The prefix is the slave descriptor.
 */
#define MEM1_COMPONENT_TYPE altera_avalon_onchip_memory2
#define MEM1_COMPONENT_NAME mem1
#define MEM1_BASE 0x0
#define MEM1_SPAN 4096
#define MEM1_END 0xfff
#define MEM1_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define MEM1_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define MEM1_CONTENTS_INFO ""
#define MEM1_DUAL_PORT 1
#define MEM1_GUI_RAM_BLOCK_TYPE AUTO
#define MEM1_INIT_CONTENTS_FILE soc_mem1
#define MEM1_INIT_MEM_CONTENT 1
#define MEM1_INSTANCE_ID NONE
#define MEM1_NON_DEFAULT_INIT_FILE_ENABLED 0
#define MEM1_RAM_BLOCK_TYPE AUTO
#define MEM1_READ_DURING_WRITE_MODE OLD_DATA
#define MEM1_SINGLE_CLOCK_OP 1
#define MEM1_SIZE_MULTIPLE 1
#define MEM1_SIZE_VALUE 4096
#define MEM1_WRITABLE 1
#define MEM1_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define MEM1_MEMORY_INFO_GENERATE_DAT_SYM 1
#define MEM1_MEMORY_INFO_GENERATE_HEX 1
#define MEM1_MEMORY_INFO_HAS_BYTE_LANE 0
#define MEM1_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define MEM1_MEMORY_INFO_MEM_INIT_DATA_WIDTH 16
#define MEM1_MEMORY_INFO_MEM_INIT_FILENAME soc_mem1

/*
 * Macros for device 'mem2', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'MEM2_'.
 * The prefix is the slave descriptor.
 */
#define MEM2_COMPONENT_TYPE altera_avalon_onchip_memory2
#define MEM2_COMPONENT_NAME mem2
#define MEM2_BASE 0x1000
#define MEM2_SPAN 4096
#define MEM2_END 0x1fff
#define MEM2_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define MEM2_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define MEM2_CONTENTS_INFO ""
#define MEM2_DUAL_PORT 1
#define MEM2_GUI_RAM_BLOCK_TYPE AUTO
#define MEM2_INIT_CONTENTS_FILE soc_mem2
#define MEM2_INIT_MEM_CONTENT 1
#define MEM2_INSTANCE_ID NONE
#define MEM2_NON_DEFAULT_INIT_FILE_ENABLED 0
#define MEM2_RAM_BLOCK_TYPE AUTO
#define MEM2_READ_DURING_WRITE_MODE OLD_DATA
#define MEM2_SINGLE_CLOCK_OP 1
#define MEM2_SIZE_MULTIPLE 1
#define MEM2_SIZE_VALUE 4096
#define MEM2_WRITABLE 1
#define MEM2_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define MEM2_MEMORY_INFO_GENERATE_DAT_SYM 1
#define MEM2_MEMORY_INFO_GENERATE_HEX 1
#define MEM2_MEMORY_INFO_HAS_BYTE_LANE 0
#define MEM2_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define MEM2_MEMORY_INFO_MEM_INIT_DATA_WIDTH 16
#define MEM2_MEMORY_INFO_MEM_INIT_FILENAME soc_mem2


#endif /* _ALTERA_HPS_H_ */
